#!/usr/bin/env bash

export DOTFILES="${DOTFILES:-$HOME/dotfiles}"
export PATH="$HOME/.cargo/bin:$PATH"

# XDG base directories
# see https://specifications.freedesktop.org/basedir/latest/
# httbps://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export BROWSER="${BROWSER:-firefox}"
export TERMINAL="${TERMINAL:-alacritty}"
export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-nvim}"

export LANG="${LANG:-en_US.UTF-8}"

export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-i3}"
export DESKTOP_SESSION="${DESKTOP_SESSION:-i3}"

if [ -r "$DOTFILES/local.env" ]; then
	set -a
	. "$DOTFILES/local.env"
	set +a
fi

# Done
cd $HOME
if [ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
    exec i3
else
    exec dbus-run-session -- i3
fi
