# vim:syntax=i3config:

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# kill focused window
bindsym $mod+Shift+q kill

# start a terminal
bindsym $mod+Return exec $term

# start rofi
bindsym $mod+d exec --no-startup-id i3-msg 'exec --no-startup-id rofi -i -show drun -modi drun -show-icons'
